name: Run script on all platforms

on:
  push:
  pull_request:

jobs:
  run-script:
    name: Run on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run:
          pip install numpy
          pip install torch
          pip install keopscore@git+https://github.com/Louis-Pujol/keops.git@windows-compatibility#subdirectory=keopscore
          pip install pykeops@git+https://github.com/Louis-Pujol/keops.git@windows-compatibility#subdirectory=pykeops

      - name: Test keops bindings
        run: python test_bindings.py
