name: Run script on all platforms

on:
  push:
  pull_request:

jobs:
  run-script:
    name: Run on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install dependencies and test bindings
        run: |
          pip install numpy
          pip install torch
          pip install keopscore@git+https://github.com/Louis-Pujol/keops.git@windows-compatibility#subdirectory=keopscore
          pip install pykeops@git+https://github.com/Louis-Pujol/keops.git@windows-compatibility#subdirectory=pykeops
          

      - name: Run test_bindings.py
        run: |
          python test_bindings.py

